
--[[
	jinyan.zhang
	战斗相关的头文件
--]]

require("app.battle.obj.AnimationFigure")
require("app.battle.obj.Monomer")
require("app.battle.obj.Hero")
require("app.battle.obj.ArrowTower")
require("app.battle.obj.HeroArms")
require("app.battle.obj.AICastle")
require("app.battle.obj.Monster")
require("app.battle.obj.CopyHeroArms")
require("app.battle.obj.HeroMgr")
require("app.battle.effectMgr.EffectMgr")
require("app.battle.common.CreateAnimation")
require("app.battle.common.BattleCommon")
require("app.battle.common.AnmationHelp")
require("app.battle.action.Shake")
require("app.battle.logic.TouchLayer")
require("app.battle.logic.BattleLogic")
require("app.battle.skill.SkillBase")
require("app.battle.skill.SkillRegion")
require("app.battle.skill.SkillFly")
require("app.battle.skill.SkillFallingRocks")
require("app.battle.skill.SkillBowling")
require("app.battle.skill.SkillRocket")
require("app.battle.skill.SkillHeroRocket")
require("app.battle.skill.SkillBuffBase")
require("app.battle.skill.SkillMgr")
