--[[
	EquipList.lua
--]]

local EquipList=
{
	[100001] = { el_id=100001,el_name="武器1",el_icon="weapon_1_1",el_type=1,el_level=1,el_quality=1,el_attack=10,el_defence=0,el_hp=10,el_fight=30,el_footmanattack=0.1,el_footmandefence=0,el_footmanhp=0,el_cavalryattack=0,el_cavalrydefence=0,el_cavalryhp=0,el_archerattack=0,el_archerdefence=0,el_archerhp=0,el_magicattack=0,el_magicdefence=0,el_magichp=0,el_tankattack=0,el_tankdefence=0,el_tankhp=0,el_weight=0,el_speed=0,},
	[100002] = { el_id=100002,el_name="衣服1",el_icon="clothes_1_1",el_type=2,el_level=1,el_quality=1,el_attack=0,el_defence=20,el_hp=0,el_fight=30,el_footmanattack=0,el_footmandefence=0.1,el_footmanhp=0,el_cavalryattack=0,el_cavalrydefence=0,el_cavalryhp=0,el_archerattack=0,el_archerdefence=0,el_archerhp=0,el_magicattack=0,el_magicdefence=0,el_magichp=0,el_tankattack=0,el_tankdefence=0,el_tankhp=0,el_weight=0,el_speed=0,},
	[100003] = { el_id=100003,el_name="腰带1",el_icon="belt_1_1",el_type=3,el_level=1,el_quality=1,el_attack=0,el_defence=10,el_hp=10,el_fight=30,el_footmanattack=0,el_footmandefence=0,el_footmanhp=0.1,el_cavalryattack=0,el_cavalrydefence=0,el_cavalryhp=0,el_archerattack=0,el_archerdefence=0,el_archerhp=0,el_magicattack=0,el_magicdefence=0,el_magichp=0,el_tankattack=0,el_tankdefence=0,el_tankhp=0,el_weight=0,el_speed=0,},
	[100004] = { el_id=100004,el_name="护腕1",el_icon="gauntlet_1_1",el_type=4,el_level=1,el_quality=1,el_attack=10,el_defence=0,el_hp=10,el_fight=30,el_footmanattack=0,el_footmandefence=0,el_footmanhp=0,el_cavalryattack=0,el_cavalrydefence=0.1,el_cavalryhp=0,el_archerattack=0,el_archerdefence=0,el_archerhp=0,el_magicattack=0,el_magicdefence=0,el_magichp=0,el_tankattack=0,el_tankdefence=0,el_tankhp=0,el_weight=0,el_speed=0,},
	[100005] = { el_id=100005,el_name="裤子1",el_icon="trousers_1_1",el_type=5,el_level=1,el_quality=1,el_attack=0,el_defence=20,el_hp=0,el_fight=30,el_footmanattack=0,el_footmandefence=0,el_footmanhp=0,el_cavalryattack=0,el_cavalrydefence=0,el_cavalryhp=0,el_archerattack=0,el_archerdefence=0,el_archerhp=0,el_magicattack=0,el_magicdefence=0,el_magichp=0,el_tankattack=0,el_tankdefence=0,el_tankhp=0,el_weight=0.1,el_speed=0,},
	[100006] = { el_id=100006,el_name="鞋子1",el_icon="shoes_1_1",el_type=6,el_level=1,el_quality=1,el_attack=10,el_defence=10,el_hp=0,el_fight=30,el_footmanattack=0,el_footmandefence=0,el_footmanhp=0,el_cavalryattack=0,el_cavalrydefence=0,el_cavalryhp=0,el_archerattack=0,el_archerdefence=0,el_archerhp=0,el_magicattack=0,el_magicdefence=0,el_magichp=0,el_tankattack=0,el_tankdefence=0,el_tankhp=0,el_weight=0,el_speed=0.1,},
	[100007] = { el_id=100007,el_name="武器2",el_icon="weapon_5_1",el_type=1,el_level=5,el_quality=2,el_attack=20,el_defence=0,el_hp=20,el_fight=60,el_footmanattack=0.2,el_footmandefence=0,el_footmanhp=0,el_cavalryattack=0,el_cavalrydefence=0,el_cavalryhp=0,el_archerattack=0,el_archerdefence=0,el_archerhp=0,el_magicattack=0,el_magicdefence=0,el_magichp=0,el_tankattack=0,el_tankdefence=0,el_tankhp=0,el_weight=0,el_speed=0,},
	[100008] = { el_id=100008,el_name="衣服2",el_icon="clothes_5_1",el_type=2,el_level=5,el_quality=2,el_attack=0,el_defence=40,el_hp=0,el_fight=60,el_footmanattack=0,el_footmandefence=0.2,el_footmanhp=0,el_cavalryattack=0,el_cavalrydefence=0,el_cavalryhp=0,el_archerattack=0,el_archerdefence=0,el_archerhp=0,el_magicattack=0,el_magicdefence=0,el_magichp=0,el_tankattack=0,el_tankdefence=0,el_tankhp=0,el_weight=0,el_speed=0,},
	[100009] = { el_id=100009,el_name="腰带2",el_icon="belt_5_1",el_type=3,el_level=5,el_quality=2,el_attack=0,el_defence=20,el_hp=20,el_fight=60,el_footmanattack=0,el_footmandefence=0,el_footmanhp=0.2,el_cavalryattack=0,el_cavalrydefence=0,el_cavalryhp=0,el_archerattack=0,el_archerdefence=0,el_archerhp=0,el_magicattack=0,el_magicdefence=0,el_magichp=0,el_tankattack=0,el_tankdefence=0,el_tankhp=0,el_weight=0,el_speed=0,},
	[100010] = { el_id=100010,el_name="护腕2",el_icon="gauntlet_5_1",el_type=4,el_level=5,el_quality=2,el_attack=20,el_defence=0,el_hp=20,el_fight=60,el_footmanattack=0,el_footmandefence=0,el_footmanhp=0,el_cavalryattack=0,el_cavalrydefence=0.2,el_cavalryhp=0,el_archerattack=0,el_archerdefence=0,el_archerhp=0,el_magicattack=0,el_magicdefence=0,el_magichp=0,el_tankattack=0,el_tankdefence=0,el_tankhp=0,el_weight=0,el_speed=0,},
	[100011] = { el_id=100011,el_name="裤子2",el_icon="trousers_5_1",el_type=5,el_level=5,el_quality=2,el_attack=0,el_defence=40,el_hp=0,el_fight=60,el_footmanattack=0,el_footmandefence=0,el_footmanhp=0,el_cavalryattack=0,el_cavalrydefence=0,el_cavalryhp=0,el_archerattack=0,el_archerdefence=0,el_archerhp=0,el_magicattack=0,el_magicdefence=0,el_magichp=0,el_tankattack=0,el_tankdefence=0,el_tankhp=0,el_weight=0.2,el_speed=0,},
	[100012] = { el_id=100012,el_name="鞋子2",el_icon="shoes_5_1",el_type=6,el_level=5,el_quality=2,el_attack=20,el_defence=20,el_hp=0,el_fight=60,el_footmanattack=0,el_footmandefence=0,el_footmanhp=0,el_cavalryattack=0,el_cavalrydefence=0,el_cavalryhp=0,el_archerattack=0,el_archerdefence=0,el_archerhp=0,el_magicattack=0,el_magicdefence=0,el_magichp=0,el_tankattack=0,el_tankdefence=0,el_tankhp=0,el_weight=0,el_speed=0.2,},
}
return EquipList
