--[[
	ItemTemplate.lua
--]]

local ItemTemplate=
{
	[1] = { it_id=1,it_name="500粮食",it_icon="item0001",it_description="使用后增加粮食500",it_type=3,it_subtype=1,it_quality=1,it_inmall=1,it_beuse=1,it_price=10,it_incresegrain=500,it_incresewood=0,it_increseiron=0,it_incresemithril=0,it_incresegold=0,it_turbotype=0,it_turbotime=0,it_addgrainyield=0,it_addwoodyield=0,it_addironyield=0,it_addmithrilyield=0,it_protectcastle=0,it_nospy=0,it_addattack=0,it_addattacktime=0,it_adddefence=0,it_adddefencetime=0,it_castleshape=0,it_castleshapetime=0,it_reduceburning=0,it_reducetime=0,it_mimicrytime =0,it_increasesoldier=0,it_increasetime=0,},
	[2] = { it_id=2,it_name="500木材",it_icon="item0002",it_description="使用后增加木材500",it_type=3,it_subtype=2,it_quality=1,it_inmall=1,it_beuse=1,it_price=10,it_incresegrain=0,it_incresewood=500,it_increseiron=0,it_incresemithril=0,it_incresegold=0,it_turbotype=0,it_turbotime=0,it_addgrainyield=0,it_addwoodyield=0,it_addironyield=0,it_addmithrilyield=0,it_protectcastle=0,it_nospy=0,it_addattack=0,it_addattacktime=0,it_adddefence=0,it_adddefencetime=0,it_castleshape=0,it_castleshapetime=0,it_reduceburning=0,it_reducetime=0,it_mimicrytime =0,it_increasesoldier=0,it_increasetime=0,},
	[3] = { it_id=3,it_name="500铁矿",it_icon="item0003",it_description="使用后增加铁矿500",it_type=3,it_subtype=3,it_quality=1,it_inmall=1,it_beuse=1,it_price=10,it_incresegrain=0,it_incresewood=0,it_increseiron=500,it_incresemithril=0,it_incresegold=0,it_turbotype=0,it_turbotime=0,it_addgrainyield=0,it_addwoodyield=0,it_addironyield=0,it_addmithrilyield=0,it_protectcastle=0,it_nospy=0,it_addattack=0,it_addattacktime=0,it_adddefence=0,it_adddefencetime=0,it_castleshape=0,it_castleshapetime=0,it_reduceburning=0,it_reducetime=0,it_mimicrytime =0,it_increasesoldier=0,it_increasetime=0,},
	[4] = { it_id=4,it_name="500秘银",it_icon="item0004",it_description="使用后增加秘银500",it_type=3,it_subtype=4,it_quality=1,it_inmall=1,it_beuse=1,it_price=10,it_incresegrain=0,it_incresewood=0,it_increseiron=0,it_incresemithril=500,it_incresegold=0,it_turbotype=0,it_turbotime=0,it_addgrainyield=0,it_addwoodyield=0,it_addironyield=0,it_addmithrilyield=0,it_protectcastle=0,it_nospy=0,it_addattack=0,it_addattacktime=0,it_adddefence=0,it_adddefencetime=0,it_castleshape=0,it_castleshapetime=0,it_reduceburning=0,it_reducetime=0,it_mimicrytime =0,it_increasesoldier=0,it_increasetime=0,},
	[5] = { it_id=5,it_name="500金币",it_icon="item0005",it_description="使用后增加金币500",it_type=3,it_subtype=5,it_quality=1,it_inmall=0,it_beuse=1,it_price=0,it_incresegrain=0,it_incresewood=0,it_increseiron=0,it_incresemithril=0,it_incresegold=500,it_turbotype=0,it_turbotime=0,it_addgrainyield=0,it_addwoodyield=0,it_addironyield=0,it_addmithrilyield=0,it_protectcastle=0,it_nospy=0,it_addattack=0,it_addattacktime=0,it_adddefence=0,it_adddefencetime=0,it_castleshape=0,it_castleshapetime=0,it_reduceburning=0,it_reducetime=0,it_mimicrytime =0,it_increasesoldier=0,it_increasetime=0,},
	[6] = { it_id=6,it_name="加速1小时",it_icon="item0006",it_description="加速1小时",it_type=2,it_subtype=0,it_quality=3,it_inmall=1,it_beuse=0,it_price=100,it_incresegrain=0,it_incresewood=0,it_increseiron=0,it_incresemithril=0,it_incresegold=0,it_turbotype=9,it_turbotime=60,it_addgrainyield=0,it_addwoodyield=0,it_addironyield=0,it_addmithrilyield=0,it_protectcastle=0,it_nospy=0,it_addattack=0,it_addattacktime=0,it_adddefence=0,it_adddefencetime=0,it_castleshape=0,it_castleshapetime=0,it_reduceburning=0,it_reducetime=0,it_mimicrytime =0,it_increasesoldier=0,it_increasetime=0,},
	[7] = { it_id=7,it_name="建造加速1小时",it_icon="item0007",it_description="建造加速1小时",it_type=2,it_subtype=0,it_quality=1,it_inmall=1,it_beuse=0,it_price=100,it_incresegrain=0,it_incresewood=0,it_increseiron=0,it_incresemithril=0,it_incresegold=0,it_turbotype=1,it_turbotime=60,it_addgrainyield=0,it_addwoodyield=0,it_addironyield=0,it_addmithrilyield=0,it_protectcastle=0,it_nospy=0,it_addattack=0,it_addattacktime=0,it_adddefence=0,it_adddefencetime=0,it_castleshape=0,it_castleshapetime=0,it_reduceburning=0,it_reducetime=0,it_mimicrytime =0,it_increasesoldier=0,it_increasetime=0,},
	[8] = { it_id=8,it_name="训练加速1小时",it_icon="item0008",it_description="训练加速1小时",it_type=2,it_subtype=0,it_quality=1,it_inmall=1,it_beuse=0,it_price=100,it_incresegrain=0,it_incresewood=0,it_increseiron=0,it_incresemithril=0,it_incresegold=0,it_turbotype=2,it_turbotime=60,it_addgrainyield=0,it_addwoodyield=0,it_addironyield=0,it_addmithrilyield=0,it_protectcastle=0,it_nospy=0,it_addattack=0,it_addattacktime=0,it_adddefence=0,it_adddefencetime=0,it_castleshape=0,it_castleshapetime=0,it_reduceburning=0,it_reducetime=0,it_mimicrytime =0,it_increasesoldier=0,it_increasetime=0,},
	[9] = { it_id=9,it_name="陷阱建造加速1小时",it_icon="item0009",it_description="陷阱建造加速1小时",it_type=2,it_subtype=0,it_quality=1,it_inmall=1,it_beuse=0,it_price=100,it_incresegrain=0,it_incresewood=0,it_increseiron=0,it_incresemithril=0,it_incresegold=0,it_turbotype=3,it_turbotime=60,it_addgrainyield=0,it_addwoodyield=0,it_addironyield=0,it_addmithrilyield=0,it_protectcastle=0,it_nospy=0,it_addattack=0,it_addattacktime=0,it_adddefence=0,it_adddefencetime=0,it_castleshape=0,it_castleshapetime=0,it_reduceburning=0,it_reducetime=0,it_mimicrytime =0,it_increasesoldier=0,it_increasetime=0,},
	[10] = { it_id=10,it_name="治疗加速1小时",it_icon="item0010",it_description="治疗加速1小时",it_type=2,it_subtype=0,it_quality=1,it_inmall=1,it_beuse=0,it_price=100,it_incresegrain=0,it_incresewood=0,it_increseiron=0,it_incresemithril=0,it_incresegold=0,it_turbotype=4,it_turbotime=60,it_addgrainyield=0,it_addwoodyield=0,it_addironyield=0,it_addmithrilyield=0,it_protectcastle=0,it_nospy=0,it_addattack=0,it_addattacktime=0,it_adddefence=0,it_adddefencetime=0,it_castleshape=0,it_castleshapetime=0,it_reduceburning=0,it_reducetime=0,it_mimicrytime =0,it_increasesoldier=0,it_increasetime=0,},
	[11] = { it_id=11,it_name="科技研究加速1小时",it_icon="item0011",it_description="科技研究加速1小时",it_type=2,it_subtype=0,it_quality=1,it_inmall=1,it_beuse=0,it_price=100,it_incresegrain=0,it_incresewood=0,it_increseiron=0,it_incresemithril=0,it_incresegold=0,it_turbotype=5,it_turbotime=60,it_addgrainyield=0,it_addwoodyield=0,it_addironyield=0,it_addmithrilyield=0,it_protectcastle=0,it_nospy=0,it_addattack=0,it_addattacktime=0,it_adddefence=0,it_adddefencetime=0,it_castleshape=0,it_castleshapetime=0,it_reduceburning=0,it_reducetime=0,it_mimicrytime =0,it_increasesoldier=0,it_increasetime=0,},
	[12] = { it_id=12,it_name="防御塔升级道具",it_icon="item0012",it_description="防御塔升级道具",it_type=4,it_subtype=0,it_quality=2,it_inmall=1,it_beuse=0,it_price=1,it_incresegrain=0,it_incresewood=0,it_increseiron=0,it_incresemithril=0,it_incresegold=0,it_turbotype=0,it_turbotime=0,it_addgrainyield=0,it_addwoodyield=0,it_addironyield=0,it_addmithrilyield=0,it_protectcastle=0,it_nospy=0,it_addattack=0,it_addattacktime=0,it_adddefence=0,it_adddefencetime=0,it_castleshape=0,it_castleshapetime=0,it_reduceburning=0,it_reducetime=0,it_mimicrytime =0,it_increasesoldier=0,it_increasetime=0,},
	[13] = { it_id=13,it_name="英雄训练加速1小时",it_icon="item0013",it_description="英雄训练加速1小时",it_type=2,it_subtype=0,it_quality=1,it_inmall=1,it_beuse=0,it_price=100,it_incresegrain=0,it_incresewood=0,it_increseiron=0,it_incresemithril=0,it_incresegold=0,it_turbotype=6,it_turbotime=60,it_addgrainyield=0,it_addwoodyield=0,it_addironyield=0,it_addmithrilyield=0,it_protectcastle=0,it_nospy=0,it_addattack=0,it_addattacktime=0,it_adddefence=0,it_adddefencetime=0,it_castleshape=0,it_castleshapetime=0,it_reduceburning=0,it_reducetime=0,it_mimicrytime =0,it_increasesoldier=0,it_increasetime=0,},
	[14] = { it_id=14,it_name="战争守护8小时",it_icon="item0014",it_description="战争守护8小时",it_type=1,it_subtype=0,it_quality=1,it_inmall=1,it_beuse=1,it_price=100,it_incresegrain=0,it_incresewood=0,it_increseiron=0,it_incresemithril=0,it_incresegold=0,it_turbotype=0,it_turbotime=0,it_addgrainyield=0,it_addwoodyield=0,it_addironyield=0,it_addmithrilyield=0,it_protectcastle=480,it_nospy=0,it_addattack=0,it_addattacktime=0,it_adddefence=0,it_adddefencetime=0,it_castleshape=0,it_castleshapetime=0,it_reduceburning=0,it_reducetime=0,it_mimicrytime =0,it_increasesoldier=0,it_increasetime=0,},
	[15] = { it_id=15,it_name="攻击加成",it_icon="item0015",it_description="全军攻击加成20%，持续时间2小时",it_type=1,it_subtype=0,it_quality=2,it_inmall=1,it_beuse=1,it_price=100,it_incresegrain=0,it_incresewood=0,it_increseiron=0,it_incresemithril=0,it_incresegold=0,it_turbotype=0,it_turbotime=0,it_addgrainyield=0,it_addwoodyield=0,it_addironyield=0,it_addmithrilyield=0,it_protectcastle=0,it_nospy=0,it_addattack=0.2,it_addattacktime=120,it_adddefence=0,it_adddefencetime=0,it_castleshape=0,it_castleshapetime=0,it_reduceburning=0,it_reducetime=0,it_mimicrytime =0,it_increasesoldier=0,it_increasetime=0,},
	[16] = { it_id=16,it_name="防御加成",it_icon="item0016",it_description="全军防御加成20%，持续时间2小时",it_type=1,it_subtype=0,it_quality=2,it_inmall=1,it_beuse=1,it_price=100,it_incresegrain=0,it_incresewood=0,it_increseiron=0,it_incresemithril=0,it_incresegold=0,it_turbotype=0,it_turbotime=0,it_addgrainyield=0,it_addwoodyield=0,it_addironyield=0,it_addmithrilyield=0,it_protectcastle=0,it_nospy=0,it_addattack=0,it_addattacktime=0,it_adddefence=0.2,it_adddefencetime=120,it_castleshape=0,it_castleshapetime=0,it_reduceburning=0,it_reducetime=0,it_mimicrytime =0,it_increasesoldier=0,it_increasetime=0,},
	[17] = { it_id=17,it_name="战争迷雾8小时",it_icon="item0017",it_description="使用后无法被人侦查，持续8小时",it_type=1,it_subtype=0,it_quality=1,it_inmall=1,it_beuse=1,it_price=100,it_incresegrain=0,it_incresewood=0,it_increseiron=0,it_incresemithril=0,it_incresegold=0,it_turbotype=0,it_turbotime=0,it_addgrainyield=0,it_addwoodyield=0,it_addironyield=0,it_addmithrilyield=0,it_protectcastle=0,it_nospy=480,it_addattack=0,it_addattacktime=0,it_adddefence=0,it_adddefencetime=0,it_castleshape=0,it_castleshapetime=0,it_reduceburning=0,it_reducetime=0,it_mimicrytime =0,it_increasesoldier=0,it_increasetime=0,},
	[18] = { it_id=18,it_name="城堡装扮-古堡",it_icon="item0018",it_description="使用后使大地图上城堡外形改变为古堡，持续1小时",it_type=4,it_subtype=0,it_quality=1,it_inmall=1,it_beuse=1,it_price=200,it_incresegrain=0,it_incresewood=0,it_increseiron=0,it_incresemithril=0,it_incresegold=0,it_turbotype=0,it_turbotime=0,it_addgrainyield=0,it_addwoodyield=0,it_addironyield=0,it_addmithrilyield=0,it_protectcastle=0,it_nospy=0,it_addattack=0,it_addattacktime=0,it_adddefence=0,it_adddefencetime=0,it_castleshape=1,it_castleshapetime=60,it_reduceburning=0,it_reducetime=0,it_mimicrytime =0,it_increasesoldier=0,it_increasetime=0,},
	[19] = { it_id=19,it_name="减少消耗",it_icon="item0019",it_description="使用后使士兵的粮食消耗减少10%，持续1小时",it_type=1,it_subtype=0,it_quality=1,it_inmall=1,it_beuse=1,it_price=100,it_incresegrain=0,it_incresewood=0,it_increseiron=0,it_incresemithril=0,it_incresegold=0,it_turbotype=0,it_turbotime=0,it_addgrainyield=0,it_addwoodyield=0,it_addironyield=0,it_addmithrilyield=0,it_protectcastle=0,it_nospy=0,it_addattack=0,it_addattacktime=0,it_adddefence=0,it_adddefencetime=0,it_castleshape=0,it_castleshapetime=0,it_reduceburning=0.1,it_reducetime=60,it_mimicrytime =0,it_increasesoldier=0,it_increasetime=0,},
	[20] = { it_id=20,it_name="伪装术-1小时",it_icon="item0020",it_description="使用后使敌方侦查的时候部队数量都变为2倍，持续时间1小时",it_type=1,it_subtype=0,it_quality=1,it_inmall=1,it_beuse=1,it_price=100,it_incresegrain=0,it_incresewood=0,it_increseiron=0,it_incresemithril=0,it_incresegold=0,it_turbotype=0,it_turbotime=0,it_addgrainyield=0,it_addwoodyield=0,it_addironyield=0,it_addmithrilyield=0,it_protectcastle=0,it_nospy=0,it_addattack=0,it_addattacktime=0,it_adddefence=0,it_adddefencetime=0,it_castleshape=0,it_castleshapetime=0,it_reduceburning=0,it_reducetime=0,it_mimicrytime =60,it_increasesoldier=0,it_increasetime=0,},
	[21] = { it_id=21,it_name="出征上限提升",it_icon="item0021",it_description="使用后使出征时可以英雄可以带领的部队数量上限提升20%，持续时间1小时",it_type=1,it_subtype=0,it_quality=1,it_inmall=1,it_beuse=1,it_price=100,it_incresegrain=0,it_incresewood=0,it_increseiron=0,it_incresemithril=0,it_incresegold=0,it_turbotype=0,it_turbotime=0,it_addgrainyield=0,it_addwoodyield=0,it_addironyield=0,it_addmithrilyield=0,it_protectcastle=0,it_nospy=0,it_addattack=0,it_addattacktime=0,it_adddefence=0,it_adddefencetime=0,it_castleshape=0,it_castleshapetime=0,it_reduceburning=0,it_reducetime=0,it_mimicrytime =0,it_increasesoldier=0.2,it_increasetime=60,},
	[22] = { it_id=22,it_name="建筑移动",it_icon="item0022",it_description="用于城内建筑移动的道具",it_type=4,it_subtype=0,it_quality=1,it_inmall=1,it_beuse=0,it_price=200,it_incresegrain=0,it_incresewood=0,it_increseiron=0,it_incresemithril=0,it_incresegold=0,it_turbotype=0,it_turbotime=0,it_addgrainyield=0,it_addwoodyield=0,it_addironyield=0,it_addmithrilyield=0,it_protectcastle=0,it_nospy=0,it_addattack=0,it_addattacktime=0,it_adddefence=0,it_adddefencetime=0,it_castleshape=0,it_castleshapetime=0,it_reduceburning=0,it_reducetime=0,it_mimicrytime =0,it_increasesoldier=0,it_increasetime=0,},
	[23] = { it_id=23,it_name="修改昵称",it_icon="item0023",it_description="修改昵称",it_type=4,it_subtype=0,it_quality=1,it_inmall=1,it_beuse=0,it_price=100,it_incresegrain=0,it_incresewood=0,it_increseiron=0,it_incresemithril=0,it_incresegold=0,it_turbotype=0,it_turbotime=0,it_addgrainyield=0,it_addwoodyield=0,it_addironyield=0,it_addmithrilyield=0,it_protectcastle=0,it_nospy=0,it_addattack=0,it_addattacktime=0,it_adddefence=0,it_adddefencetime=0,it_castleshape=0,it_castleshapetime=0,it_reduceburning=0,it_reducetime=0,it_mimicrytime =0,it_increasesoldier=0,it_increasetime=0,},
	[24] = { it_id=24,it_name="修改形象",it_icon="item0024",it_description="修改形象",it_type=4,it_subtype=0,it_quality=1,it_inmall=1,it_beuse=0,it_price=100,it_incresegrain=0,it_incresewood=0,it_increseiron=0,it_incresemithril=0,it_incresegold=0,it_turbotype=0,it_turbotime=0,it_addgrainyield=0,it_addwoodyield=0,it_addironyield=0,it_addmithrilyield=0,it_protectcastle=0,it_nospy=0,it_addattack=0,it_addattacktime=0,it_adddefence=0,it_adddefencetime=0,it_castleshape=0,it_castleshapetime=0,it_reduceburning=0,it_reducetime=0,it_mimicrytime =0,it_increasesoldier=0,it_increasetime=0,},
}
return ItemTemplate
