
require("app.ui.territory.TerritoryView")
require("app.ui.territory.TerritoryCommand")
require("app.ui.territory.TerritoryMenuBaseView")
require("app.ui.territory.TerritoryResBuildingMenu")
require("app.ui.territory.TerritoryTowerMenu")
require("app.ui.territory.TerritoryWallMenu")
require("app.ui.territory.ResBuildingUpLevel")
require("app.ui.territory.TowerUpLevel")
require("app.ui.territory.WallUpLevel")
require("app.ui.territory.TerritoryModel")
require("app.ui.territory.TerritoryService")
require("app.ui.territory.TerritoryAcceService")
require("app.ui.territory.ResBuildingAcceView")
require("app.ui.territory.TowerAcceView")
require("app.ui.territory.WallAcceView")
require("app.ui.territory.TerritoryDefView")

