
--[[
	jinyan.zhang
	配置头文件
--]]

require("app.config.GameConfig")
require("app.config.battleConfig.ArcherConfig")
require("app.config.battleConfig.ArrowTowerConfig")
require("app.config.battleConfig.MagicTowerConfig")
require("app.config.battleConfig.TurretConfig")
require("app.config.battleConfig.BowCavalryConfig")
require("app.config.battleConfig.CatapultConfig")
require("app.config.battleConfig.CrossbowmenConfig")
require("app.config.battleConfig.KnightConfig")
require("app.config.battleConfig.MarinesConfig")
require("app.config.battleConfig.MasterConfig")
require("app.config.battleConfig.ShieldSoldierConfig")
require("app.config.battleConfig.TankConfig")
require("app.config.battleConfig.WarlockConfig")
require("app.config.battleConfig.FallingRocksConfig")
require("app.config.battleConfig.BowlingConfig")
require("app.config.battleConfig.RocketConfig")
require("app.config.battleConfig.HeroRocekConfig")
require("app.config.battleConfig.BattleConfig")
require("app.config.common.ArmsConfig")
require("app.config.common.WorldMapConfig")
require("app.config.common.CommonConfig")
require(CONFIG_SRC_PRE_PATH .. "LanguageText")
require(CONFIG_SRC_PRE_PATH .. "HintClient")
require(CONFIG_SRC_PRE_PATH .. "CommonStr")
require(CONFIG_SRC_PRE_PATH .. "ErrorMsgProp")
require("app.config.common.BuildPosConfig")
require("app.config.common.BuildingUpLvConfig")
require("app.config.common.BuildingTypeConfig")
require("app.config.common.BuildingEffectConfig")
require("app.config.common.CopyMapConfig")
require("app.config.common.ResourcebuildingEffectConfig")
require("app.config.common.MonsterListConfig")
require("app.config.common.AidEffectConfig")
require("app.config.common.CampEffectConfig")
require("app.config.common.StorehouseEffectConfig")
require("app.config.common.WallEffectConfig")
require("app.config.common.TrapListConfig")
require("app.config.common.CharacterListConfig")
require("app.config.common.CharacterUpdataConfig")
require("app.config.common.ItemTemplateConfig")
require("app.config.common.TowerEffectConfig")
require("app.config.common.TrainEffectConfig")
require("app.config.common.HeroFaceConfig")
require("app.config.common.EquipConfig")
require("app.config.common.PubEffectConfig")
require("app.config.common.CastleplusListConfig")
require("app.config.common.PlusItemConfig")
require("app.config.common.SkillConfig")
require("app.config.common.CastleEffectConfig")
require("app.config.common.LandUnLockConfig")
require("app.config.common.ArmsAttributeConfig")
require("app.config.common.TechListConfig")
require("app.config.common.TechUpgradeConfig")
require("app.config.common.LordHeadConfig")
require("app.config.common.LordSkillConfig")
require("app.config.common.TalentListConfig")
require("app.config.common.TalentUpgradeConfig")
require("app.config.common.LordSkillConfig")
require("app.config.common.OutTowerEffectConfig")
require("app.config.common.OutResBuildingEffectConfig")
require("app.config.common.OutWallConfig")
require("app.config.common.DropListConfig")



